In [28]:
import numpy as np

In [29]:
l=[]
l1=[]
i=1
while i<=10:
        if i<6:
            j = int(input("enter a number:"))
            l.append(j)
        else:     
            r =int(input("enter a number:"))
            l1.append(r)
        i = i+1

enter a number:45
enter a number:67
enter a number:89
enter a number:1
enter a number:47
enter a number:3
enter a number:56
enter a number:78
enter a number:98
enter a number:77


In [30]:
arr=np.array([l])
arr1=np.array([l1])
new=np.concatenate((arr, arr1));
print(new)


[[45 67 89  1 47]
 [ 3 56 78 98 77]]


In [31]:
new.sort()
print(new)

[[ 1 45 47 67 89]
 [ 3 56 77 78 98]]
