In [1]:
import numpy as np


In [5]:
arr1 = np.array([[1, 2,3],[4,5,6]])
print ("1st Input array : \n", arr1)    
arr2 = np.array([[ 8, 5, 9] ,[2,5,8]]) 
print ("2nd Input array : \n", arr2)

1st Input array : 
 [[1 2 3]
 [4 5 6]]
2nd Input array : 
 [[8 5 9]
 [2 5 8]]


In [7]:
arr = np.hstack((arr1, arr2)) 
print ("Output horizontally stacked array:\n ", arr) 

Output horizontally stacked array:
  [[1 2 3 8 5 9]
 [4 5 6 2 5 8]]


In [10]:
arr3= np.vstack((arr1, arr2)) 
print ("Output stacked array :\n ", arr3) 

Output stacked array :
  [[1 2 3]
 [4 5 6]
 [8 5 9]
 [2 5 8]]
